# Generated by Django 4.1.3 on 2023-05-23 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0002_remove_ticket_additional_guests_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="additional_guests_count",
        ),
    ]
