# Generated by Django 4.1.3 on 2023-05-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0004_guest"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="name",
            field=models.CharField(default=None, max_length=15),
        ),
    ]
