# Generated by Django 4.1.3 on 2023-05-25 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0005_guest_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="ticket",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="guest",
                to="ticketApp.ticket",
            ),
        ),
    ]
