# Generated by Django 4.1.3 on 2023-05-25 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0006_alter_guest_ticket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
