# Generated by Django 4.1.3 on 2023-05-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0008_guest_date_of_visit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="date_of_visit",
            field=models.DateField(editable=False, null=True),
        ),
    ]
