# Generated by Django 4.1.3 on 2023-05-26 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0009_alter_guest_date_of_visit"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="media/guest_pictures/"
            ),
        ),
    ]
