# Generated by Django 4.1.3 on 2023-05-26 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0010_guest_picture"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="guest",
            name="picture",
        ),
        migrations.AddField(
            model_name="guest",
            name="picture_selection",
            field=models.CharField(
                blank=True,
                choices=[
                    ("boy_1", "Boy 1"),
                    ("boy_2", "Boy 2"),
                    ("boy", "Boy"),
                    ("catwoman", "Catwoman"),
                    ("girl_1", "Girl 1"),
                    ("girl_2", "Girl 2"),
                    ("girl", "Girl"),
                    ("punk", "Punk"),
                    ("woman", "Woman"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
