# Generated by Django 4.1.3 on 2023-05-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0011_remove_guest_picture_guest_picture_selection"),
    ]

    operations = [
        migrations.RenameField(
            model_name="guest",
            old_name="picture_selection",
            new_name="picture",
        ),
    ]
