# Generated by Django 4.1.3 on 2023-05-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0012_rename_picture_selection_guest_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
