# Generated by Django 4.1.3 on 2023-05-31 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticketApp", "0013_alter_ticket_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="guest",
            name="name",
            field=models.CharField(
                blank=True, default="Visitor", max_length=20, null=True
            ),
        ),
    ]
