# Generated by Django 4.1.3 on 2023-05-22 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="email address"
                    ),
                ),
                ("date_of_visit", models.DateField()),
                ("additional_guests", models.BooleanField(default=False)),
                ("ticket_id", models.CharField(max_length=255, unique=True)),
                ("salt", models.CharField(max_length=255)),
            ],
        ),
    ]
