# Generated by Django 4.1.3 on 2023-05-22 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientApp", "0002_ticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="additional_guests",
        ),
    ]
