# Generated by Django 4.1.3 on 2023-05-22 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clientApp", "0004_ticket"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ticket",
        ),
    ]
