# Generated by Django 4.1.3 on 2023-05-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clientApp", "0006_customuser_height"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(default="Undefined", max_length=30),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
    ]
