# Generated by Django 4.1.3 on 2023-05-27 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ridereservation",
            name="reservation_id",
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ridereservation",
            name="validated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="rideschedule",
            name="date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="rideschedule",
            name="reservations",
            field=models.ManyToManyField(blank=True, to="queueApp.ridereservation"),
        ),
        migrations.AlterField(
            model_name="rideschedule",
            name="end_time",
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name="rideschedule",
            name="start_time",
            field=models.TimeField(null=True),
        ),
    ]
