# Generated by Django 4.1.3 on 2023-05-27 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueApp", "0002_ridereservation_reservation_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ridereservation",
            name="id",
        ),
        migrations.RemoveField(
            model_name="rideschedule",
            name="id",
        ),
        migrations.AddField(
            model_name="ridereservation",
            name="reservation_ticket_id",
            field=models.CharField(editable=False, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="rideschedule",
            name="schedule_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="ridereservation",
            name="reservation_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
