# Generated by Django 4.1.3 on 2023-05-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("queueApp", "0004_alter_ridereservation_reservation_id_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ridereservation",
            name="additional_guests",
        ),
        migrations.RemoveField(
            model_name="ridereservation",
            name="user",
        ),
        migrations.AlterField(
            model_name="ridereservation",
            name="end_time",
            field=models.TimeField(editable=False),
        ),
        migrations.AlterField(
            model_name="ridereservation",
            name="start_time",
            field=models.TimeField(),
        ),
    ]
