# Generated by Django 4.1.3 on 2023-05-28 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("queueApp", "0006_ridereservation_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="RideSchedule",
        ),
    ]
