# Generated by Django 4.1.3 on 2023-05-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rideApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkEmployee",
            fields=[
                ("employee_id", models.AutoField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("date_of_birth", models.DateField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                (
                    "work_place",
                    models.CharField(
                        choices=[
                            ("ride", "Ride"),
                            ("shop", "Shop"),
                            ("restaurant", "Restaurant"),
                        ],
                        max_length=15,
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("join_date", models.DateField()),
                ("shift_start", models.TimeField()),
                ("shift_end", models.TimeField()),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True, unique=True),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideApp.themeparkarea",
                    ),
                ),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideApp.themepark",
                    ),
                ),
            ],
        ),
    ]
