# Generated by Django 4.1.3 on 2023-05-19 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rideApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestaurantType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("fast_food", "Fast Food"),
                            ("casual_dining", "Casual Dining"),
                            ("fine_dining", "Fine Dining"),
                            ("cafe", "Cafe"),
                            ("buffet", "Buffet"),
                            ("Breakfast", "Breakfast"),
                            ("Lunch", "Lunch"),
                            ("Dinner", "Dinner"),
                            ("American", "American"),
                            ("Asian", "Asian"),
                            ("Bakery", "Bakery"),
                            ("Healthy", "Healthy"),
                            ("Mediterranean", "Mediterranean"),
                            ("Mexican", "Mexican"),
                            ("Steakhouse", "Steakhouse"),
                            ("Vegetarian", "Vegetarian"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Restaurant",
            fields=[
                ("restaurant_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("brief_text", models.CharField(max_length=250)),
                ("long_description", models.TextField()),
                (
                    "thumbnail",
                    models.ImageField(default=None, upload_to="restaurant_thumbnails/"),
                ),
                ("restaurant_types", models.CharField(default=None, max_length=250)),
                ("opening_hour", models.TimeField()),
                ("closing_hour", models.TimeField()),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideApp.themeparkarea",
                    ),
                ),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rideApp.themepark",
                    ),
                ),
            ],
        ),
    ]
